namespace UmbracoTestData
{
    internal static class Constants
    {
        internal static class Misc
        {
            internal const string AngularPrefix = "]}', ";
        } 
        internal static class Paths
        {
            internal const string Login = "/backoffice/UmbracoApi/Authentication/PostLogin";
            internal const string CreateDocType = "/backoffice/UmbracoApi/ContentType/PostSave";
            internal const string CreateContent = "/backoffice/UmbracoApi/Content/PostSave";
        } 
        internal static class Data
        {
            internal const string ShortString = "Lorem ipsum dolor sit amet";
            internal const string LongString = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam egestas eget mi in congue. Sed id congue justo. Cras sodales nisi lacus, ac efficitur tortor suscipit eget. Donec dignissim turpis in lorem dapibus laoreet. Etiam eleifend mi in euismod egestas. Praesent ultrices metus est, in rhoncus quam tincidunt nec. Aliquam luctus arcu ac mauris laoreet, id efficitur ex iaculis. Vestibulum maximus fermentum purus, vitae fringilla magna. Nam quis magna imperdiet, rutrum nibh id, mattis neque. Aliquam et leo nisl.

In eu diam nec quam commodo mattis. Donec leo purus, pellentesque quis vehicula ut, placerat eu velit. Pellentesque ac nisl et mauris viverra vehicula eu sit amet ligula. Praesent at elementum leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi metus elit, feugiat nec arcu id, aliquet dictum risus. Sed feugiat, tortor ac rhoncus semper, lorem neque auctor diam, posuere tempus velit lectus eget sapien. Morbi aliquam risus quis tempor tincidunt. Aenean molestie sed ante et tempus. Morbi imperdiet ex enim, in sagittis turpis cursus vel. Nullam vitae pellentesque mi. Maecenas varius sapien tellus, non laoreet arcu imperdiet id. Vestibulum vehicula nec felis a rhoncus.

Pellentesque aliquet nisi id justo sodales, sit amet lobortis urna scelerisque. Mauris commodo libero et consectetur aliquam. Sed fringilla ex eu dui pharetra, et malesuada odio finibus. Nulla dictum libero justo, ac finibus orci vestibulum id. Integer ullamcorper quis diam quis vehicula. Phasellus nibh orci, interdum sodales tortor in, vehicula efficitur mauris. Duis quis congue odio. Fusce egestas sit amet lorem ut suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed luctus dolor. Praesent orci sapien, suscipit quis placerat in, ultrices eleifend nunc. Aliquam erat volutpat. Aliquam a finibus libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum massa arcu, sagittis eget tempor et, eleifend id sapien.

Etiam non dui malesuada, varius leo in, aliquam eros. In hac habitasse platea dictumst. Nullam eget lorem sed ante tempor interdum non interdum lacus. Vivamus ultricies fermentum viverra. Ut non pretium ipsum, vel consequat ipsum. Nam laoreet bibendum laoreet. Mauris rhoncus at tellus quis ultricies. Maecenas scelerisque lacinia pellentesque. Fusce ac ullamcorper ante. Vivamus vel sodales lorem, lobortis gravida metus. Donec faucibus sapien nec lacus porttitor, a fermentum nisl rhoncus. Donec blandit, felis nec laoreet fringilla, augue felis eleifend justo, eget interdum ligula enim ac neque. Duis feugiat egestas nulla, placerat dignissim leo vulputate ac. Aliquam nec lacinia diam.

Etiam tempor magna auctor metus molestie, sit amet imperdiet urna dignissim. Praesent dolor eros, mollis eget mi et, vulputate placerat massa. Phasellus sit amet luctus tortor. Praesent euismod eget sapien vel viverra. Nulla ligula leo, placerat nec dapibus dictum, accumsan ac orci. Suspendisse nunc magna, scelerisque sit amet facilisis quis, eleifend nec nunc. Vestibulum dolor lectus, consequat nec maximus in, auctor in ex. Nulla quis dolor nulla. Nulla condimentum ultrices mauris, quis tempor turpis tristique at. Maecenas vel urna sit amet risus suscipit laoreet. Aliquam malesuada, neque quis posuere ornare, orci dolor finibus lectus, in venenatis massa neque auctor enim.

Donec fringilla nisi in nunc fermentum posuere. Vivamus at urna eu nibh fringilla laoreet vitae et lorem. Maecenas tempor, quam ut volutpat ultrices, quam turpis ullamcorper dui, ut viverra eros nunc a nibh. Mauris augue quam, accumsan scelerisque nunc varius, luctus rhoncus tortor. Ut vel cursus tellus. Nulla facilisi. Aenean feugiat tristique sollicitudin. Morbi tincidunt vehicula nunc, ac fermentum lacus rhoncus nec. Quisque nec turpis tristique, accumsan erat mattis, pretium tortor. Suspendisse gravida turpis sed justo convallis tempor. Vivamus mollis, eros vitae tempor tristique, enim est ornare purus, ac fermentum ex tortor vel tellus. Maecenas at rutrum nisl.

Nunc congue nisl ipsum, at pellentesque sapien gravida in. Curabitur ut mattis libero. Quisque faucibus erat non est lacinia eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas vitae egestas est. Nullam ut viverra lacus. Phasellus dignissim nulla sed quam aliquam, vel elementum magna facilisis. In maximus lorem ac porttitor vestibulum. Quisque sit amet augue enim. Aliquam quis neque iaculis, mollis libero non, varius nisl. Nam ultricies orci et leo sodales maximus. Fusce faucibus pellentesque ligula eu pulvinar. Quisque metus urna, mollis quis molestie in, consectetur a nulla. Duis a sapien at neque sodales ornare id quis lectus. Pellentesque eu convallis orci, vel rutrum eros.

Nunc dapibus est at felis finibus, eget mollis erat varius. Nam pharetra turpis ac urna auctor rutrum. Morbi ornare ipsum et dui vulputate gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer pulvinar sollicitudin lorem, fringilla sodales justo pulvinar eu. Mauris pulvinar accumsan lorem, eu ultrices turpis suscipit in. Sed nunc arcu, tristique eu diam et, hendrerit faucibus libero. Aliquam dictum auctor purus egestas venenatis. Nulla sit amet blandit enim, eget consectetur turpis. Cras ornare felis vel quam commodo dictum. Morbi a venenatis quam, ut gravida turpis.

Nunc euismod imperdiet est, eu tempor urna aliquam non. Curabitur vel felis fermentum, condimentum erat vel, consectetur ex. Etiam orci sapien, porttitor tincidunt faucibus eu, volutpat quis sem. Nullam tortor lacus, interdum a accumsan ut, fringilla vel justo. Aenean quis lobortis dui. Quisque vel lorem nec nisi ultricies malesuada. Nullam vulputate vitae elit quis rhoncus. Curabitur feugiat diam sapien, quis rutrum tortor porttitor sit amet. Donec vestibulum ligula lectus, scelerisque cursus dui aliquet ut. Curabitur congue porta libero. Integer a nisi ex. Donec odio purus, molestie id turpis quis, pretium posuere enim. Proin pellentesque velit luctus tristique venenatis. Etiam malesuada varius sapien ut condimentum. Integer dignissim, nibh eleifend dictum varius, purus nisl tristique est, a egestas nunc ex ut massa. Maecenas non fringilla turpis.

Vivamus nulla odio, suscipit accumsan ipsum eget, sollicitudin ornare mi. Fusce dapibus felis odio, sit amet hendrerit purus placerat vitae. Sed elementum eros vitae nisi scelerisque sagittis. Praesent non sagittis nisi. Maecenas laoreet lacus at sapien ultricies, in egestas mauris aliquam. Vestibulum ac lorem est. Praesent tempor, metus ac efficitur rhoncus, est diam vehicula ipsum, rhoncus sollicitudin felis turpis vitae neque. Etiam aliquam ut nunc eu ultrices. Maecenas vestibulum sodales lacus ac condimentum.

Vivamus ac lectus a nisi ullamcorper ultrices nec at nisi. Ut iaculis semper mi ac consequat. Donec venenatis a nisi non sagittis. Vestibulum sodales suscipit arcu, et imperdiet lacus pulvinar quis. Suspendisse eget ipsum non ligula accumsan varius. Pellentesque nulla erat, laoreet eget porttitor id, commodo sit amet lectus. Nulla pretium, sem non pretium eleifend, felis ipsum facilisis felis, non posuere enim risus ac sem. Morbi non lorem non lorem sagittis tincidunt sit amet sed metus.

Morbi ac dapibus lectus. Duis at lectus dui. In scelerisque justo in augue hendrerit pulvinar. Nunc vitae tristique nunc, sed pellentesque odio. Vestibulum id fermentum justo, at cursus tellus. Suspendisse mollis justo et massa varius, vitae sodales lorem finibus. Donec cursus feugiat sapien pulvinar semper. Praesent at fringilla dolor. In consequat ultricies quam vel tincidunt. Praesent tempus odio nec mi aliquet, et mollis quam luctus. In hac habitasse platea dictumst. Vivamus vestibulum arcu tortor, id mattis lectus dictum quis.

Sed at dolor diam. Aenean eget egestas tellus, a mollis purus. Aliquam non mi ex. Donec nunc odio, iaculis pharetra rutrum nec, cursus vitae ante. Pellentesque vehicula, purus et rhoncus tincidunt, nisi felis viverra nibh, sed condimentum sem ex a nulla. Ut vestibulum consequat felis a molestie. Pellentesque vulputate ex ac pretium viverra. Donec ac nulla vitae tellus tempus tempor a sed sem. Suspendisse at lacus aliquet sem lacinia posuere. Maecenas auctor, odio in elementum convallis, turpis diam facilisis est, eget dapibus eros neque ut quam. Etiam eleifend vehicula turpis. Pellentesque efficitur nibh et lorem luctus malesuada. Aenean malesuada, lectus vel malesuada vulputate, justo est accumsan augue, nec condimentum magna dui sit amet nibh. Donec accumsan convallis augue, at volutpat lectus ornare nec. Nulla mattis ex id dui maximus, eget tempor elit dapibus.

Aenean sodales mollis ipsum, quis faucibus libero commodo in. Quisque quis mattis leo. Nulla eget luctus leo. Sed posuere malesuada ante, vitae condimentum justo pulvinar ut. Sed scelerisque, nunc vel ullamcorper tincidunt, ante metus sollicitudin turpis, et facilisis massa mi eget nulla. Etiam a ante massa. Nulla facilisi. Sed at semper justo, vitae gravida augue.

Nam cursus vehicula felis, ac interdum risus. Maecenas pulvinar eu ante nec pulvinar. Etiam hendrerit orci pharetra urna bibendum, quis convallis ex tincidunt. Nullam vel finibus mi. Pellentesque et sem ac neque suscipit dignissim. Phasellus id sem vehicula, elementum nulla non, placerat sapien. Cras id urna sed turpis lacinia pulvinar. Nam vel elit pulvinar, sollicitudin lorem ac, tincidunt quam.

Donec enim lorem, tristique sed condimentum sed, imperdiet vel nibh. Maecenas id finibus urna. Nullam lobortis mauris eu nibh auctor, eu condimentum diam efficitur. Curabitur porta varius congue. Proin sit amet est placerat, ullamcorper urna ut, egestas enim. Ut sit amet molestie ligula. Quisque nec ultrices velit, non interdum dui. Suspendisse potenti. Ut fringilla orci non placerat vestibulum. Proin pulvinar justo eu lacus molestie, at feugiat orci efficitur. Nulla ornare vel dui sed imperdiet. Nulla vitae finibus justo, vitae mollis libero. Vivamus purus tellus, porta quis placerat vitae, pellentesque ac ligula. Ut dapibus eros id lorem lacinia maximus eget consectetur enim. Sed consectetur diam vitae enim ultrices commodo.

Nam volutpat turpis metus, eu cursus dolor porttitor id. Mauris mollis imperdiet placerat. Vestibulum nec bibendum nisl. Mauris id semper turpis, quis tincidunt felis. Morbi id vehicula tellus. Quisque dictum felis sem, ac rutrum quam pharetra quis. Donec tincidunt, neque in blandit tempor, leo urna hendrerit nisi, a finibus sem libero vitae mi. Sed convallis velit lectus, a eleifend risus vestibulum eu. Sed at libero sagittis, volutpat massa sit amet, rutrum velit. Fusce eu enim a magna varius pulvinar. Nulla id sapien semper, sagittis augue in, molestie eros. In molestie quis tellus et rutrum. Nunc rutrum euismod dignissim.

Fusce efficitur id dui at varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rutrum enim dui, ac sodales est sodales non. Phasellus in velit a ligula viverra ultrices. Nam in pharetra nisi. Proin iaculis, odio at tincidunt ullamcorper, enim tellus suscipit nulla, nec venenatis neque purus et arcu. Donec nec feugiat erat. Nunc pharetra molestie odio et tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet viverra metus, eget eleifend risus. Curabitur vitae felis fringilla, dictum ex et, sagittis nisi. Nullam metus massa, facilisis non dui nec, molestie vulputate felis. Quisque malesuada felis leo, id luctus ligula tempus in. Duis sagittis dui ac nibh mollis, eget varius diam sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed ullamcorper, nisi consequat imperdiet eleifend, massa elit placerat dui, ut molestie ante felis ut lectus. In iaculis fringilla facilisis. Donec condimentum enim eu odio aliquet euismod. Phasellus elit risus, placerat ac sagittis aliquam, pulvinar non urna. Integer elit eros, consequat at mi ac, molestie fermentum nisl. Maecenas turpis elit, ornare ac diam sit amet, consectetur consequat nisl. Aliquam sed arcu vitae odio molestie congue. Quisque vitae orci eget arcu aliquam venenatis at quis nisl. Mauris a magna id leo viverra vehicula. Donec elementum quis nisl eu fermentum. Nunc placerat nisl non lobortis tempor. Cras aliquet tempus urna, in lobortis leo vulputate eu.

Integer facilisis elit non ullamcorper laoreet. Nunc eros magna, cursus in varius at, posuere et ante. Ut facilisis enim a enim dapibus rhoncus. Sed rhoncus odio sit amet condimentum eleifend. Proin interdum tellus non ante dapibus, sit amet scelerisque ex rutrum. Phasellus nulla felis, pretium eget consectetur vitae, condimentum in nulla. Aenean cursus, risus id pretium finibus, magna velit faucibus lacus, quis blandit mi neque in mauris. Aenean scelerisque lectus urna.

Mauris vel purus leo. Nam in odio lorem. In nisl turpis, suscipit nec ornare vitae, lobortis eu sapien. Aliquam et lacus at velit auctor imperdiet maximus a metus. Aenean sit amet consequat lorem, eget iaculis elit. Suspendisse nulla leo, porta sed scelerisque vitae, lacinia vel erat. Proin arcu turpis, aliquet vel dolor eu, bibendum posuere mi. Sed ut neque ut odio congue pulvinar. Sed scelerisque luctus egestas. In vestibulum et magna quis pellentesque. Duis vel lacus nisi. Etiam a diam vitae nibh volutpat eleifend a vel mi. Curabitur fringilla sem elit, sed semper turpis euismod ornare. Nulla est tortor, pellentesque vestibulum scelerisque at, mattis at ipsum. Mauris maximus efficitur nibh quis faucibus.";

        } 
    }
}